POST http://localhost:3001/api/blog
Content-Type: application/json

{
  "title": "Ram raheem",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 7,
  "id":"69c3a7fa482e56c05669f8e4"
}